language: cpp
sudo: required
dist: trusty
services:
  - docker
os:
  - linux
env:
  - JOB=check_style
addons:
  ssh_known_hosts: 13.229.163.131
before_install:
  # For pylint dockstring checker
  - sudo pip install pre-commit pylint pytest astroid isort
  - |
    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
script:
  - "travis_wait 30 sleep 1800 &"
  - |
    # 43min timeout
    pre-commit install
    pre-commit run -a
    if [ $? -eq 0 ]; then true; else exit 1; fi;
notifications:
  email:
    on_success: change
    on_failure: always
